-- MySQL Script generated by MySQL Workbench
-- Wed Apr 17 20:03:27 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Campanha`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Campanha` (
  `idEvento` INT NOT NULL,
  `data` DATETIME NULL,
  PRIMARY KEY (`idEvento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`BancoDeSangue`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`BancoDeSangue` (
  `idBancoDeSangue` INT GENERATED ALWAYS AS () VIRTUAL,
  `NomeBancoDeSangue` VARCHAR(45) NULL,
  `fkEventoBancoDeSangue` INT GENERATED ALWAYS AS () VIRTUAL,
  PRIMARY KEY (`idBancoDeSangue`),
  INDEX `fk_BancoDeSangue_Evento1_idx` (`fkEventoBancoDeSangue` ASC) VISIBLE,
  CONSTRAINT `fk_BancoDeSangue_Evento1`
    FOREIGN KEY (`fkEventoBancoDeSangue`)
    REFERENCES `mydb`.`Campanha` (`idEvento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Endereco` (
  `idEnderecoDoador` INT NOT NULL,
  `cep` CHAR(8) NULL,
  `RUA` VARCHAR(45) NULL,
  `NUMERO` CHAR(8) NULL,
  `BAIRRO` VARCHAR(45) NULL,
  `fkBancoDeSangue` INT NOT NULL,
  `fkEvento` INT NOT NULL,
  PRIMARY KEY (`idEnderecoDoador`),
  INDEX `fk_Endereco_Ong1_idx` (`fkBancoDeSangue` ASC) VISIBLE,
  INDEX `fk_Endereco_Evento1_idx` (`fkEvento` ASC) VISIBLE,
  CONSTRAINT `fk_Endereco_Ong1`
    FOREIGN KEY (`fkBancoDeSangue`)
    REFERENCES `mydb`.`BancoDeSangue` (`idBancoDeSangue`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Endereco_Evento1`
    FOREIGN KEY (`fkEvento`)
    REFERENCES `mydb`.`Campanha` (`idEvento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `idUsuario` INT NOT NULL,
  `nomeDoador` VARCHAR(45) NULL,
  `dataNascimento` DATE NULL,
  `emailDoador` VARCHAR(45) NULL,
  `sexo` TINYINT NULL,
  `senha` VARCHAR(45) NULL,
  `fkEvento` INT NOT NULL,
  `fkEndereco` INT NOT NULL,
  PRIMARY KEY (`idUsuario`),
  INDEX `fk_Usuario_Evento1_idx` (`fkEvento` ASC) VISIBLE,
  INDEX `fk_Usuario_Endereco1_idx` (`fkEndereco` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_Evento1`
    FOREIGN KEY (`fkEvento`)
    REFERENCES `mydb`.`Campanha` (`idEvento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_Endereco1`
    FOREIGN KEY (`fkEndereco`)
    REFERENCES `mydb`.`Endereco` (`idEnderecoDoador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Contato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Contato` (
  `idContato` INT NOT NULL,
  `telefone` INT NULL,
  `celular` INT NULL,
  `fkContatoDoador` INT NOT NULL,
  `fkBancoDeSangue` INT NOT NULL,
  `fkEventoContato` INT NOT NULL,
  PRIMARY KEY (`idContato`),
  INDEX `fk_Contato_doador1_idx` (`fkContatoDoador` ASC) VISIBLE,
  INDEX `fk_Contato_Ong1_idx` (`fkBancoDeSangue` ASC) VISIBLE,
  INDEX `fk_Contato_Evento1_idx` (`fkEventoContato` ASC) VISIBLE,
  CONSTRAINT `fk_Contato_doador1`
    FOREIGN KEY (`fkContatoDoador`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Contato_Ong1`
    FOREIGN KEY (`fkBancoDeSangue`)
    REFERENCES `mydb`.`BancoDeSangue` (`idBancoDeSangue`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Contato_Evento1`
    FOREIGN KEY (`fkEventoContato`)
    REFERENCES `mydb`.`Campanha` (`idEvento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`numeroTelefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`numeroTelefone` (
  `idnumeroTelefone` INT NOT NULL,
  `dd` CHAR(2) NULL,
  `numero` CHAR(9) NULL,
  `fkContato` INT NOT NULL,
  PRIMARY KEY (`idnumeroTelefone`),
  INDEX `fk_numeroTelefone_Contato1_idx` (`fkContato` ASC) VISIBLE,
  CONSTRAINT `fk_numeroTelefone_Contato1`
    FOREIGN KEY (`fkContato`)
    REFERENCES `mydb`.`Contato` (`idContato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`NivelDeAcesso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`NivelDeAcesso` (
  `editar` TINYINT NULL,
  `deletar` TINYINT NULL,
  `idNivelDeAcesso` INT NOT NULL,
  PRIMARY KEY (`idNivelDeAcesso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Local`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Local` (
  `idLocal` INT NOT NULL,
  `longitude` VARCHAR(45) NULL,
  `latitude` VARCHAR(45) NULL,
  PRIMARY KEY (`idLocal`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Evento` (
  `Evento_idEvento` INT NOT NULL,
  `Local_idLocal` INT NOT NULL,
  PRIMARY KEY (`Evento_idEvento`, `Local_idLocal`),
  INDEX `fk_Evento_has_Local_Local1_idx` (`Local_idLocal` ASC) VISIBLE,
  INDEX `fk_Evento_has_Local_Evento1_idx` (`Evento_idEvento` ASC) VISIBLE,
  CONSTRAINT `fk_Evento_has_Local_Evento1`
    FOREIGN KEY (`Evento_idEvento`)
    REFERENCES `mydb`.`Campanha` (`idEvento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Evento_has_Local_Local1`
    FOREIGN KEY (`Local_idLocal`)
    REFERENCES `mydb`.`Local` (`idLocal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`GrupoNivelAcesso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`GrupoNivelAcesso` (
  `fkIdUsuario` INT NOT NULL,
  `fkIdNivelAcesso` INT NOT NULL,
  `Admin` INT NULL,
  `Comum` INT NULL,
  PRIMARY KEY (`fkIdUsuario`, `fkIdNivelAcesso`),
  INDEX `fk_Usuario_has_NivelDeAcesso_NivelDeAcesso1_idx` (`fkIdNivelAcesso` ASC) VISIBLE,
  INDEX `fk_Usuario_has_NivelDeAcesso_Usuario1_idx` (`fkIdUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_has_NivelDeAcesso_Usuario1`
    FOREIGN KEY (`fkIdUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_has_NivelDeAcesso_NivelDeAcesso1`
    FOREIGN KEY (`fkIdNivelAcesso`)
    REFERENCES `mydb`.`NivelDeAcesso` (`idNivelDeAcesso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
